# Generated by Django 2.2 on 2019-04-23 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('comentarios', models.TextField(max_length=500)),
                ('activo', models.BooleanField()),
                ('fecha_creaccion', models.DateField(auto_now_add=True)),
                ('fecha_cambio', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Creatividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10)),
                ('cadena', models.CharField(max_length=50)),
                ('direccion', models.TextField(max_length=300)),
                ('cp', models.IntegerField()),
                ('ciudad', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=50)),
                ('prioridad', models.IntegerField(max_length=2)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='montador',
            name='usuario',
            field=models.OneToOneField(limit_choices_to={'is_montador': True}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Pdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('anchoTotal', models.IntegerField()),
                ('anchoVista', models.IntegerField()),
                ('altoTotal', models.IntegerField()),
                ('altoVista', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('composicion', models.BooleanField()),
                ('instaladores', models.IntegerField()),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pdv')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TipoPdi')),
            ],
        ),
        migrations.CreateModel(
            name='Campana_pdV_pdI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>')),
                ('fecha_creaccion', models.DateField(auto_now_add=True)),
                ('fecha_cambio', models.DateField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Campana')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pdi')),
                ('pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pdv')),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='creatividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Creatividad'),
        ),
        migrations.AddField(
            model_name='campana',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Material'),
        ),
    ]
