# Generated by Django 2.2 on 2019-04-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Logo'),
        ),
    ]
