# Generated by Django 2.2 on 2019-04-24 01:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190423_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='fecha_finalizado',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana_pdv_pdi',
            name='idioma',
            field=models.CharField(choices=[('esp', 'Español'), ('cat', 'Catalán'), ('gal', 'Gallego'), ('eu', 'Euskera'), ('eng', 'Inglés')], default='esp', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campana_pdv_pdi',
            name='montador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Montador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pdv',
            name='prioridad',
            field=models.IntegerField(),
        ),
    ]
