# Generated by Django 2.2 on 2019-04-11 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190411_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='id_slug',
            new_name='slug',
        ),
    ]
