# Generated by Django 2.2 on 2019-04-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190424_0158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campana_pdv_pdi',
            old_name='idiom',
            new_name='idioma',
        ),
    ]
