# Generated by Django 2.2 on 2019-04-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190424_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='fecha_finalizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
