# Generated by Django 2.2 on 2019-04-24 03:38

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190424_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='nombre',
            field=models.CharField(default='aviles2', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana_pdv_pdi',
            name='image',
            field=models.ImageField(upload_to=main.models.pdi_image_path),
        ),
    ]
