# Generated by Django 2.2 on 2019-04-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_campana_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='cliente',
            field=models.ManyToManyField(to='main.Cliente'),
        ),
    ]
