# Generated by Django 2.2 on 2019-04-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_pdv_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='pdvs',
            field=models.ManyToManyField(through='application.Campana_pdV_pdI', to='application.Pdv'),
        ),
    ]
