# Generated by Django 2.2 on 2019-04-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_campana_pdvs'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana_pdv_pdi',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('pendiente', 'pendiente'), ('incidencia', 'incidencia')], default='pendiente', max_length=15),
            preserve_default=False,
        ),
    ]
