# Generated by Django 2.2 on 2019-04-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_campana_pdv_pdi_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='campana_asociada',
            field=models.ManyToManyField(through='main.Campana_pdV_pdI', to='main.Campana'),
        ),
    ]
