# Generated by Django 2.2 on 2019-04-28 16:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_pdv_campana_asociada'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana_Pdv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CampanapdV_pdI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.pdi_image_path)),
                ('idioma', models.CharField(choices=[('esp', 'Español'), ('cat', 'Catalán'), ('gal', 'Gallego'), ('eu', 'Euskera'), ('eng', 'Inglés')], max_length=10)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_cambio', models.DateField(auto_now=True)),
                ('Campana_Pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Campana_Pdv')),
                ('creatividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Creatividad')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Material')),
                ('montador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Montador')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pdi')),
            ],
        ),
        migrations.RemoveField(
            model_name='pdv',
            name='campana_asociada',
        ),
        migrations.AlterField(
            model_name='campana',
            name='pdvs',
            field=models.ManyToManyField(through='main.Campana_Pdv', to='main.Pdv'),
        ),
        migrations.DeleteModel(
            name='Campana_pdV_pdI',
        ),
        migrations.AddField(
            model_name='campana_pdv',
            name='campana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Campana'),
        ),
        migrations.AddField(
            model_name='campana_pdv',
            name='pdv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Pdv'),
        ),
        migrations.AddField(
            model_name='pdv',
            name='campanas',
            field=models.ManyToManyField(through='main.Campana_Pdv', to='main.Campana'),
        ),
    ]
