# Generated by Django 2.2 on 2019-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190428_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanapdv_pdi',
            name='idioma',
        ),
        migrations.AddField(
            model_name='campana_pdv',
            name='idioma',
            field=models.CharField(choices=[('esp', 'Español'), ('cat', 'Catalán'), ('gal', 'Gallego'), ('eu', 'Euskera'), ('eng', 'Inglés')], default='esp', max_length=10),
            preserve_default=False,
        ),
    ]
