# Generated by Django 2.2 on 2019-04-30 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190430_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campana',
            old_name='fecha_creaccion',
            new_name='fecha_creacion',
        ),
    ]
