# Generated by Django 2.2 on 2019-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190430_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana_pdv',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('pendiente', 'pendiente'), ('incidencia', 'incidencia')], max_length=15),
        ),
    ]
