# Generated by Django 2.2 on 2019-05-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190504_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanapdv_pdi',
            name='creatividad',
        ),
        migrations.AddField(
            model_name='campana',
            name='creatividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Creatividad'),
        ),
        migrations.AddField(
            model_name='creatividad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/creatividades'),
        ),
    ]
