# Generated by Django 2.2 on 2019-05-24 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190524_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campana',
            name='creatividad',
        ),
        migrations.AddField(
            model_name='campanapdv_pdi',
            name='creatividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.Creatividad'),
        ),
        migrations.AddField(
            model_name='creatividad',
            name='Campana',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.Campana'),
            preserve_default=False,
        ),
    ]
