# Generated by Django 2.2 on 2019-05-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190524_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatividad',
            old_name='Campana',
            new_name='campana',
        ),
        migrations.AlterField(
            model_name='creatividad',
            name='imagen',
            field=models.ImageField(default='huhu', upload_to='images/creatividades'),
            preserve_default=False,
        ),
    ]
