# Generated by Django 2.2.1 on 2019-05-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190525_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdv',
            name='cliente',
        ),
    ]
