# Generated by Django 2.2.1 on 2019-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_pdv_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanapdv_pdi',
            name='montador',
        ),
        migrations.AddField(
            model_name='campanapdv_pdi',
            name='montador',
            field=models.ManyToManyField(blank=True, null=True, to='main.Montador'),
        ),
    ]
