# Generated by Django 2.2.1 on 2019-06-12 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20190610_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanapdv_pdi',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.instalacionPdi_imagen),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=500)),
                ('tipo', models.CharField(choices=[('ok', 'ok'), ('pendiente', 'pendiente'), ('incidencia', 'incidencia')], max_length=10)),
                ('visible', models.BooleanField()),
                ('Campana_Pdv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Campana_Pdv')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
