# Generated by Django 2.2.1 on 2019-06-12 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190612_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana_pdv',
            name='fecha_cambio',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campana_pdv',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia')], max_length=15),
        ),
        migrations.AlterField(
            model_name='campana_pdv',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia')], max_length=15),
        ),
        migrations.AlterField(
            model_name='comments',
            name='tipo',
            field=models.CharField(choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia')], max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
