# Generated by Django 2.2.1 on 2019-06-12 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190612_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
