# Generated by Django 2.2.1 on 2019-06-18 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_comments_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='tipo',
            field=models.CharField(choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia'), ('admin', 'admin')], max_length=10),
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
