# Generated by Django 2.2.1 on 2019-06-19 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20190618_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cliente'),
        ),
    ]
