# Generated by Django 2.2.1 on 2019-06-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190619_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zona',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
