# Generated by Django 2.2.1 on 2019-06-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190619_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zona',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
