# Generated by Django 2.2.1 on 2019-06-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190619_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='cliente',
            field=models.ManyToManyField(to='main.Cliente'),
        ),
    ]
