# Generated by Django 2.2.1 on 2019-07-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20190715_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdv',
            name='permisos',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia'), ('pendiente', 'pendiente')], default='pendiente', max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='color',
            field=models.CharField(choices=[('red', 'rojo'), ('blue', 'azul'), ('yellow', 'amarillo'), ('violet', 'violeta'), ('green', 'verde'), ('yellow', 'amarillo'), ('black', 'negro'), ('white', 'blanco')], max_length=10),
        ),
    ]
