# Generated by Django 2.2.1 on 2019-08-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190722_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanapdv_pdi',
            name='material',
        ),
        migrations.AddField(
            model_name='pdi',
            name='material',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Material'),
        ),
    ]
