# Generated by Django 2.2.1 on 2019-08-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20190811_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='montador',
            name='comunidad',
            field=models.CharField(choices=[('AND', 'Andalucía'), ('ARA', 'Aragón'), ('AST', 'Asturias'), ('CAN', 'Cantabria'), ('CYL', 'Castilla-Leon'), ('CAT', 'Cataluña'), ('CEUTA', 'Ceuta'), ('EXT', 'Extremadura'), ('GAL', 'Galicia'), ('BAL', 'Islas Baleares'), ('RIO', 'Rioja'), ('MAD', 'Madrid'), ('MEL', 'Melilla'), ('MUR', 'Murcia'), ('NAV', 'Navarra'), ('VAL', 'Valencia')], default='MAD', max_length=50),
            preserve_default=False,
        ),
    ]
