# Generated by Django 2.2.1 on 2019-08-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_montador_comunidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='campana',
            name='comentarios',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='campana_pdv',
            name='idioma',
            field=models.CharField(blank=True, choices=[('esp', 'Español'), ('cat', 'Catalán'), ('gal', 'Gallego'), ('eu', 'Euskera'), ('eng', 'Inglés')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='tipo',
            field=models.CharField(blank=True, choices=[('ok', 'ok'), ('ko', 'ko'), ('incidencia', 'incidencia'), ('admin', 'admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='montador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='montador',
            name='comunidad',
            field=models.CharField(blank=True, choices=[('AND', 'Andalucía'), ('ARA', 'Aragón'), ('AST', 'Asturias'), ('CAN', 'Cantabria'), ('CYL', 'Castilla-Leon'), ('CAT', 'Cataluña'), ('CEUTA', 'Ceuta'), ('EXT', 'Extremadura'), ('GAL', 'Galicia'), ('BAL', 'Islas Baleares'), ('RIO', 'Rioja'), ('MAD', 'Madrid'), ('MEL', 'Melilla'), ('MUR', 'Murcia'), ('NAV', 'Navarra'), ('VAL', 'Valencia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='montador',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='montador',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='altoTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='altoVista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='anchoTotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='anchoVista',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdi',
            name='composicion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='cadena',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='cp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='direccion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='prioridad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdv',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Zona'),
        ),
    ]
